### ISSUE TITLE
Proposal Review 11/7/18

### ISSUE THREAD

**Issue by BCrawfordScott** [ibltsandwich/decypher#1]
### Schema
- Everything looks good.  Considerer making comments (and maybe even upvotes) polymorphic associations as a bonus so you can comment and upvote on both annotations and comments.

**Comment by ibltsandwich** [comment]
Thanks! I've updated my schema to reflect this change. Wondering if this is the correct implementation of a polymorphic association at the database level

**Comment by BCrawfordScott** [comment]
Polymorphics look good!  

On your sample state: Upvotes should not be it's own key in entities.  Upvotes should actually be a key inside of each upvotable entity that is simply an integer representing total upvotes.   We will keep an upvotes table in the backend, but rather than bring forward whole upvote entities to the frontend we will aggregate all the upvote information in the backend and just send total counts to the frontend.

Also, make sure to add a ui, errors, and session slice of state for your sample state.

Great work!

**Comment by ibltsandwich** [comment]
updated 👍
