### ISSUE TITLE
Review 11/14

### ISSUE THREAD

**Issue by BCrawfordScott** [ibltsandwich/decypher#2]
- [x] Make sure errors don't persist when switching between log in and sign up 
- [x] Add ability to click out of modal
- [x] Styling

All the functionality looks great, now it's time to focus 100% on styling.  Obviously we won't be able to style everything perfectly since we'll need artists, albums, etc, but we should style everything we can without that content.  Keep up the good work!

**Comment by ibltsandwich** [comment]
I believe I've addressed these issues properly and have pushed to Heroku. The only thing I'm not sure about is styling the rest of the home page.

**Comment by BCrawfordScott** [comment]
Styling: 
 - [ ] Modal is aligned above the top line of the window.  Bring it down.
 - [ ] Add a footer to the homepage with links to your github, the actual genius, etc (optional).
 - Otherwise the homepage looks good!

Functionality looks great.  Excellent work.  We'll be doing another official review tomorrow.  Kepp it up!
